[workspace]
resolver = "3"
members = [
    "gtm-core",
    "gtm-audio",
    "gtmd",
    "gtm",
    "gtm-mpris",
    "release-gen",
]

[workspace.package]
version = "0.2.78"
edition = "2024"
license = "GPL-3.0-only"
repository = "https://github.com/prjctimg/gtm.rs"
homepage = "https://github.com/prjctimg/gtm.rs"
keywords = ["music", "player", "tui", "audio", "youtube"]
categories = ["command-line-utilities", "multimedia::audio"]
readme = "README.md"

[workspace.dependencies]
gtm-core = { path = "gtm-core", version = "0.2.78" }
gtm-audio = { path = "gtm-audio", version = "0.2.78" }
gtm-mpris = { path = "gtm-mpris", version = "0.2.78" }

[profile.release]
lto = "thin"
strip = "symbols"
