[workspace]

[package]
name = "release-gen"
version = "0.2.83"
edition = "2024"
license = "GPL-3.0-only"
description = "Release asset generation helper for gtm builds"
publish = false
repository = "https://github.com/prjctimg/gtm.rs"
homepage = "https://github.com/prjctimg/gtm.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "4"

[[bin]]
name = "release-gen"
path = "src/main.rs"