[package]
name = "gtm-mpris"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "MPRIS D-Bus integration for the GTM music player daemon"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
gtm-core = { path = "../gtm-core", version = "0.1.7" }
zbus = { version = "4", features = ["tokio"] }
zvariant = "4"
tracing = "0.1"
serde = "1"
